## City Recommender app:

  In this notebook, i've tried to implement recommender engine which recommends a city based on features/attributes which you've shown interest. I've even deployed to the cloud so that anyone can access.

In [0]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
np.random.seed(42)

In [2]:
#Scraping data /gathering data
df = pd.read_html('https://www.nestpick.com/millennial-city-ranking-2018/', skiprows=0)[0]
df.columns = ['#','city', 'country','Employment Score', 'Startup Score', 'Tourism Score','Housing Score', 'Food Ranking', 'Transport Score', 'Health Rank', 'Internet Speed Score', 'University Score', 'Access to Contraceptive Score', 'Gender Equality Score', 'Immigration Tolerence', 'Personal Freedom and Choice', 'LGBT friendly Score', 'Nightlife Score', 'Beer Ranking', 'Festival Ranking', 'Total']
# df.set_index('city',inplace=True)
df.drop('#',axis=1, inplace=True)
# df.index.name= None
df.head()

city         country  ...  Festival Ranking  Total
0     Berlin         Germany  ...               8.0   7.14
1   Montréal          Canada  ...               9.0   7.10
2     London  United Kingdom  ...               7.5   6.71
3  Amsterdam     Netherlands  ...               9.7   6.63
4    Toronto          Canada  ...               9.4   6.60

[5 rows x 20 columns]

In [0]:
df.to_csv('city_ranking.csv', index=False)

Since i'm gonna use only city feature ,so i'll remove country attribute from the dataset.Also i'm not sure i'll need total feature. Let's remove them:


In [4]:
#Remove unwanted attributes
data = df.set_index('city'). iloc[:,1:-1]
data.head()

Employment Score  Startup Score  ...  Beer Ranking  Festival Ranking
city                                        ...                                
Berlin                  4.8            9.0  ...           7.0               8.0
Montréal                6.0            8.1  ...           5.1               9.0
London                  6.6            9.8  ...           2.5               7.5
Amsterdam               7.6            8.3  ...           4.8               9.7
Toronto                 6.3            9.5  ...           3.6               9.4

[5 rows x 17 columns]

In [5]:
#Convert it into integers
scores = df.set_index('city'). iloc[:,1:-1].round().astype(int)
scores.head()

Employment Score  Startup Score  ...  Beer Ranking  Festival Ranking
city                                        ...                                
Berlin                    5              9  ...             7                 8
Montréal                  6              8  ...             5                 9
London                    7             10  ...             2                 8
Amsterdam                 8              8  ...             5                10
Toronto                   6             10  ...             4                 9

[5 rows x 17 columns]

### **Why Cosine_Similarity?**

   `Cosine similarity is a metric used to determine how similar the documents are irrespective of their size.`

   That's how similarity between two vectors being calculated 
   <img src='https://www.machinelearningplus.com/wp-content/uploads/2018/10/Cosine-Similarity-Formula-1-1024x133.png?ezimgfmt=ng:webp/ngcb1'>


  If you'd wanna learn more about it,visit <a href='https://www.machinelearningplus.com/nlp/cosine-similarity/'>Here!</a>

In [6]:
#Lets calculate similarities 
cosine_similarity(scores)

array([[1.        , 0.97713728, 0.92872247, ..., 0.76064317, 0.75167047,
        0.71010911],
       [0.97713728, 1.        , 0.93991451, ..., 0.81023932, 0.79920914,
        0.79407069],
       [0.92872247, 0.93991451, 1.        , ..., 0.71449984, 0.78578921,
        0.6591375 ],
       ...,
       [0.76064317, 0.81023932, 0.71449984, ..., 1.        , 0.86622045,
        0.78358256],
       [0.75167047, 0.79920914, 0.78578921, ..., 0.86622045, 1.        ,
        0.76641919],
       [0.71010911, 0.79407069, 0.6591375 , ..., 0.78358256, 0.76641919,
        1.        ]])

Hmm.. Above cell output can be intimidating/hard to interpret the results. But we'll prettify it.

In [7]:
#Prettifying
cos = pd.DataFrame(cosine_similarity(scores), columns=scores.index, index = scores.index)
cos

city         Berlin  Montréal    London  ...    Brugge    Geneva   Bologna
city                                     ...                              
Berlin     1.000000  0.977137  0.928722  ...  0.760643  0.751670  0.710109
Montréal   0.977137  1.000000  0.939915  ...  0.810239  0.799209  0.794071
London     0.928722  0.939915  1.000000  ...  0.714500  0.785789  0.659137
Amsterdam  0.950510  0.964724  0.968212  ...  0.739985  0.795076  0.735508
Toronto    0.949095  0.971958  0.925974  ...  0.808115  0.834772  0.784293
...             ...       ...       ...  ...       ...       ...       ...
Bern       0.731924  0.788305  0.762223  ...  0.893122  0.971770  0.783118
Jerusalem  0.728269  0.788009  0.684090  ...  0.705601  0.718194  0.908752
Brugge     0.760643  0.810239  0.714500  ...  1.000000  0.866220  0.783583
Geneva     0.751670  0.799209  0.785789  ...  0.866220  1.000000  0.766419
Bologna    0.710109  0.794071  0.659137  ...  0.783583  0.766419  1.000000

[110 rows x 110 columns]

In [0]:
scores.index

Index(['Berlin', 'Montréal', 'London', 'Amsterdam', 'Toronto', 'Vancouver',
       'Barcelona', 'New York City', 'Cologne', 'Manchester',
       ...
       'Milan', 'Venice', 'Bergen', 'Cape Town', 'Innsbruck', 'Bern',
       'Jerusalem', 'Brugge', 'Geneva', 'Bologna'],
      dtype='object', name='city', length=110)

In [8]:
#Artificially create some interests which can later be used to generate recommendation:
user1 = np.random.choice(range(1,11),17).reshape(-1,17) #Reshape transforms it into two dimensional vector
user1

array([[ 7,  4,  8,  5,  7, 10,  3,  7,  8,  5,  4,  8,  8,  3,  6,  5,
         2]])

In [0]:
value = []
for index,city in enumerate(scores.index):
    city_old = scores.loc[city].values.reshape(-1,17)
    score = cosine_similarity(city_old, user1)
    value.append(score)

In [10]:
#similarity scores
value

[array([[0.89220417]]),
 array([[0.868623]]),
 array([[0.8759523]]),
 array([[0.85292868]]),
 array([[0.84175019]]),
 array([[0.81341556]]),
 array([[0.84212435]]),
 array([[0.86600226]]),
 array([[0.85371077]]),
 array([[0.90700116]]),
 array([[0.81325103]]),
 array([[0.76879045]]),
 array([[0.86254252]]),
 array([[0.8133641]]),
 array([[0.81350146]]),
 array([[0.82012368]]),
 array([[0.88076972]]),
 array([[0.87398682]]),
 array([[0.85679654]]),
 array([[0.85063264]]),
 array([[0.81284352]]),
 array([[0.85264026]]),
 array([[0.85620644]]),
 array([[0.83158741]]),
 array([[0.85837534]]),
 array([[0.88137286]]),
 array([[0.79562681]]),
 array([[0.86593748]]),
 array([[0.86272954]]),
 array([[0.80098475]]),
 array([[0.83657704]]),
 array([[0.77846585]]),
 array([[0.78030267]]),
 array([[0.8257734]]),
 array([[0.85620644]]),
 array([[0.81619864]]),
 array([[0.79903396]]),
 array([[0.79571214]]),
 array([[0.87723002]]),
 array([[0.71057267]]),
 array([[0.80414583]]),
 array([[0.78689532]]

In [11]:
similarity = pd.Series(value, index=scores.index)

#Below code outputs top recommendation for you
similarity.sort_values(ascending=False).astype(float).idxmax()

'Manchester'

Let's do create a function for above codes which recommends a city.

In [0]:
#Finding similarity between cities
def find_similarity(column, user, number):
    new_df = scores[column]
    value = []
    for index,city in enumerate(new_df.index):
        city_old = new_df.loc[city].values.reshape(-1,number)
        user = user.reshape(-1, number)
        score = cosine_similarity(city_old, user)
        value.append(score)
    similarity = pd.Series(value, index=scores.index)
    city_similar = similarity.sort_values(ascending=False).astype(float).idxmax()
    message = f'Based on your preference, {city_similar} is the best recommendation'
    return message

In [14]:
column = ['Tourism Score','Housing Score', 'Food Ranking'] #Choosing three particular columns

#NO of features
number = len(column)

#User defined interest
user = np.random.choice(range(1,10), number) # Choose 3 numbers between 1 to 10
print(find_similarity(column, user, number))

Based on your preference, Sydney is the best recommendation


In [16]:
word = 'Bologna'
if word in scores.index: #If given city present in df
    country = df.loc[df['city'] == word, 'country'].iloc[0] #country of that a city
    print(f'{word} is the capital of {country}')

    if word in df['city'].head().values:
        print('It is actually one of the top 5 cities that has pique millennial interests')

    elif word in df['city'].head(10).values:
        print('It is actually one of the top 10 cities that has pique millennial interests')

    elif word in df['city'].tail(5).values:
        print('It is actually one of the least 5 cities that has pique millennial interests')
    
else:
    print(f'Which country is {word} located in ?')

Bologna is the capital of Italy
It is actually one of the least 5 cities that has pique millennial interests


In [17]:
if word in scores.index:
    title = f'About {word}'
    subtitle = 'City Ranking in terms of Business, essentials, Openness and recreation score(over 10.0)'
    print(title)
#     print('\n')
    print(subtitle)
#     print('\n')
    for i , j in zip(list(data.loc['Berlin'].index),data.loc['Berlin']):
        print(f'{i} == {j}')

About Bologna
City Ranking in terms of Business, essentials, Openness and recreation score(over 10.0)
Employment Score == 4.8
Startup Score == 9.0
Tourism Score == 6.2
Housing Score == 5.2
Food Ranking == 7.2
Transport Score == 7.1
Health Rank == 3.9
Internet Speed Score == 5.0
University Score == 4.9
Access to Contraceptive Score == 6.9
Gender Equality Score == 7.5
Immigration Tolerence == 8.4
Personal Freedom and Choice == 7.8
LGBT friendly Score == 9.7
Nightlife Score == 10.0
Beer Ranking == 7.0
Festival Ranking == 8.0


In [18]:
sort_by_country = df[["city", "country"]].sort_values("country")
sort_by_country.head()

city    country
31  Buenos Aires  Argentina
98         Perth  Australia
93      Canberra  Australia
23        Sydney  Australia
20     Melbourne  Australia

In [0]:
location = []
for index, city, country in sort_by_country.itertuples():
    new = f'{city}, {country}'
    location.append(new)

In [26]:
location

['Buenos Aires, Argentina',
 'Perth, Australia',
 'Canberra, Australia',
 'Sydney, Australia',
 'Melbourne, Australia',
 'Adelaide, Australia',
 'Brisbane, Australia',
 'Graz, Austria',
 'Innsbruck, Austria',
 'Vienna, Austria',
 'Brugge, Belgium',
 'Antwerp, Belgium',
 'Brussels, Belgium',
 'São Paulo, Brazil',
 'Rio de Janeiro, Brazil',
 'Montréal, Canada',
 'Toronto, Canada',
 'Ottawa, Canada',
 'Vancouver, Canada',
 'Québec City, Canada',
 'Santiago de Chile, Chile',
 'Shanghai, China',
 'Beijing, China',
 'Bogotá, Colombia',
 'Medellín, Colombia',
 'Brno, Czech Republic',
 'Prague, Czech Republic',
 'Copenhagen, Denmark',
 'Helsinki, Finland',
 'Marseille, France',
 'Toulouse, France',
 'Bordeaux, France',
 'Nantes, France',
 'Lyon, France',
 'Lille, France',
 'Montpellier, France',
 'Paris, France',
 'Berlin, Germany',
 'Hamburg, Germany',
 'Cologne, Germany',
 'Frankfurt, Germany',
 'Munich, Germany',
 'Athens, Greece',
 'Hong Kong, Hong Kong SAR',
 'Budapest, Hungary',
 'Cork, 

In [20]:
list(scores.index)

['Berlin',
 'Montréal',
 'London',
 'Amsterdam',
 'Toronto',
 'Vancouver',
 'Barcelona',
 'New York City',
 'Cologne',
 'Manchester',
 'Hamburg',
 'Bristol',
 'San Francisco',
 'Austin',
 'Paris',
 'Miami',
 'Munich',
 'Lisbon',
 'Glasgow',
 'Madrid',
 'Melbourne',
 'Ottawa',
 'Birmingham',
 'Sydney',
 'Prague',
 'Vienna',
 'Québec City',
 'Auckland',
 'Los Angeles',
 'São Paulo',
 'Frankfurt',
 'Buenos Aires',
 'Mexico City',
 'Portland',
 'Chicago',
 'Nantes',
 'Budapest',
 'Copenhagen',
 'Santiago de Chile',
 'Bogotá',
 'Valencia',
 'Bangkok',
 'Dublin',
 'Lyon',
 'Philadelphia',
 'Helsinki',
 'Antwerp',
 'Porto',
 'Beijing',
 'Stockholm',
 'Denver',
 'Toulouse',
 'Kuala Lumpur',
 'Medellín',
 'Rio de Janeiro',
 'Graz',
 'Hong Kong',
 'Edinburgh',
 'Guadalajara',
 'Lille',
 'Rotterdam',
 'Taipei',
 'Coventry',
 'Moscow',
 'Seoul',
 'Adelaide',
 'Brussels',
 'Zurich',
 'Boston',
 'Oslo',
 'Monterrey',
 'Seattle',
 'Brisbane',
 'Washington, D.C.',
 'The Hague',
 'Shanghai',
 'Utrecht'

In [21]:
if word in scores.index:
    title = f'About {word}'
    subtitle = 'City Ranking in terms of Business, essentials, Openness and recreation score(over 10.0)'
    print(title)
#     print('\n')
    country = df.loc[df['city'] == word, 'country'].iloc[0]
    print(f'{word} is the capital of {country}')
    if word in df['city'].head().values:
        print('It is actually one of the top 5 cities that has pique millennial interests')
    elif word in df['city'].head(10).values:
        print('It is actually one of the top 10 cities that has pique millennial interests')
    elif word in df['city'].tail(5).values:
        print('It is actually one of the least 5 cities that has pique millennial interests')
    print(subtitle)
#     print('\n')
    
    for i , j in zip(list(data.loc['Berlin'].index),data.loc['Berlin']):
        print(f'{i} == {j}')

About Bologna
Bologna is the capital of Italy
It is actually one of the least 5 cities that has pique millennial interests
City Ranking in terms of Business, essentials, Openness and recreation score(over 10.0)
Employment Score == 4.8
Startup Score == 9.0
Tourism Score == 6.2
Housing Score == 5.2
Food Ranking == 7.2
Transport Score == 7.1
Health Rank == 3.9
Internet Speed Score == 5.0
University Score == 4.9
Access to Contraceptive Score == 6.9
Gender Equality Score == 7.5
Immigration Tolerence == 8.4
Personal Freedom and Choice == 7.8
LGBT friendly Score == 9.7
Nightlife Score == 10.0
Beer Ranking == 7.0
Festival Ranking == 8.0


In [22]:
list(zip(list(data.loc[word].index),data.loc[word]))

[('Employment Score', 5.8),
 ('Startup Score', 1.4),
 ('Tourism Score', 3.2),
 ('Housing Score', 5.1),
 ('Food Ranking', 1.7),
 ('Transport Score', 1.1),
 ('Health Rank', 9.1),
 ('Internet Speed Score', 4.6),
 ('University Score', 1.0),
 ('Access to Contraceptive Score', 3.4),
 ('Gender Equality Score', 3.3),
 ('Immigration Tolerence', 6.2),
 ('Personal Freedom and Choice', 0.8),
 ('LGBT friendly Score', 2.0),
 ('Nightlife Score', 0.9),
 ('Beer Ranking', 2.3),
 ('Festival Ranking', 2.8)]

In [0]:
#Extracting cities best features to display how it might work for you
ranking = list(zip(list(data.loc[word].index),data.loc[word]))
breakdown = pd.DataFrame(ranking, columns = ['Category','Score'])

In [24]:
breakdown

Category  Score
0                Employment Score    5.8
1                   Startup Score    1.4
2                   Tourism Score    3.2
3                   Housing Score    5.1
4                    Food Ranking    1.7
5                 Transport Score    1.1
6                     Health Rank    9.1
7            Internet Speed Score    4.6
8                University Score    1.0
9   Access to Contraceptive Score    3.4
10          Gender Equality Score    3.3
11          Immigration Tolerence    6.2
12    Personal Freedom and Choice    0.8
13            LGBT friendly Score    2.0
14                Nightlife Score    0.9
15                   Beer Ranking    2.3
16               Festival Ranking    2.8

In [25]:
word = location[1]
if word == 'others':
    great = scores[column]
else: 
    locat = word.split(',')
    great = scores[scores.index !=  locat[0]][column]
    print(locat)
great.head()

['Perth', ' Australia']


Tourism Score  Housing Score  Food Ranking
city                                                 
Berlin                 6              5             7
Montréal               6              6             5
London                10              0             2
Amsterdam              9              1             2
Toronto                4              3             6

In [27]:
location[0]

'Buenos Aires, Argentina'

In [28]:
location[0].split(',')

['Buenos Aires', ' Argentina']

In [29]:
new_df = scores[column]
new_df.shape

(110, 3)

In [30]:
great.shape

(109, 3)